### PR TITLE
Add p12 certificate connection

### PR DESCRIPTION
**Pull request by xiaolei-wei**
add p12 certificate connection

### CODE REVIEW

**Comment by SqrTT** [comment]
Hi @xiaolei-wei 
Thank you for the feature. Unfortunately, I can't merge it because it uses `readFileSync` which may cause performance issues and increase IO disk operations. I would appreciate if it may be refactored.

PS. Unfortunately, I can't do it myself since I can't verify feature because of I don't have environment with certificates

**Comment by xiaolei-wei** [comment]
> 嗨@xiaolei-wei 谢谢你的功能。不幸的是，我无法合并它，因为它使用`readFileSync`可能会导致性能问题并增加 IO 磁盘操作。如果可以重构，我将不胜感激。
> 
> PS。不幸的是，我不能自己做，因为我无法验证功能，因为我没有带证书的环境

**Comment by xiaolei-wei** [comment]
> 嗨@xiaolei-wei 谢谢你的功能。不幸的是，我无法合并它，因为它使用`readFileSync`可能会导致性能问题并增加 IO 磁盘操作。如果可以重构，我将不胜感激。
> 
> PS。不幸的是，我不能自己做，因为我无法验证功能，因为我没有带证书的环境

**Comment by xiaolei-wei** [comment]
> Hi @xiaolei-wei Thank you for the feature. Unfortunately, I can't merge it because it uses `readFileSync` which may cause performance issues and increase IO disk operations. I would appreciate if it may be refactored.
> 
> PS. Unfortunately, I can't do it myself since I can't verify feature because of I don't have environment with certificates

HI, @SqrTT , modify it and use createreadstream() function. 
please review it again and write down your ideas.
best,
xiaolei-wei

**Comment by SqrTT** [comment]
@xiaolei-wei  thank you, that's better since don't block script execution but still require read file every time.

I would suggest to modify: https://github.com/SqrTT/prophet/blob/master/src/lib/FileHelper.ts#L181-L221 `getConfig` method so it's read config once and then reuse it all the way.

PS; by the way is certificate required for debugger to work?

**Comment by xiaolei-wei** [comment]
> I would suggest to modify: https://github.com/SqrTT/prophet/blob/master/src/lib/FileHelper.ts#L181-L221 `getConfig` method so it's read config once and then reuse it all the way.

OK, I will continue.

> PS; by the way is certificate required for debugger to work?

@SqrTT , need, so there are two problems to be solved
#1. The certificate is read only once
#2. There is a certificate connection when the debugger is working

best，
xiaolei-wei

**Comment by xiaolei-wei** [comment]
HI, @SqrTT ,It seems that the debug API does not support double verification. do you have any experience debugging in staging environment? I use UX studio in Eclipse tools, also returns error.
image


Best,
xiaolei-wei

**Comment by SqrTT** [comment]
Hi @xiaolei-wei 
I've never debugged staging instance and I have no way to do it not to verify. Well, probably debugger can be skipped with certificate usage

Thank you

**Comment by xiaolei-wei** [comment]
Unable to find a way to debug in staging environment.

**Pull request closed without merging**
