### PR TITLE
Isml linter

### PR DESCRIPTION
**Pull request by FabiowQuixada**
This PR introduces the [Isml Linter]( https://www.npmjs.com/package/isml-linter) tool, which parses the template and builds a full ISML DOM, allowing the usage of powerful rules. There is a [PR to SFRA](https://github.com/SalesforceCommerceCloud/storefront-reference-architecture/pull/430#issuecomment-484597688) which should be merged soon.

I got some problem while running Prophet locally, probably due to a misconfigured launch.json file, so I need some help there, if anyone is available.

Please check the npm package for all available rules and configs. Hope this PR is useful!

Thanks!

### CODE REVIEW

**Comment by SqrTT** [comment]
Hi @FabiowQuixada 
Thank you for contribution. Meanwhile the extension already has linter which is based on [htmlhint](https://www.npmjs.com/package/htmlhint). Is there reason to introduce another one?

PS. htmlhint has bigger community so it may be better choose in long perspective.

**Comment by SGD1953** [comment]
Could we maybe make it configurable so that the developers can choose which one to use?

**Comment by SqrTT** [comment]
isml-linter can be used as separate plugin https://marketplace.visualstudio.com/items?itemName=fabiowquixada.vscode-isml-linter

**Comment by FabiowQuixada** [comment]
> Hi @FabiowQuixada
> Thank you for contribution. Meanwhile the extension already has linter which is based on [htmlhint](https://www.npmjs.com/package/htmlhint). Is there reason to introduce another one?
> 
> PS. htmlhint has bigger community so it may be better choose in long perspective.

Hello @SqrTT , thanks for that. From what I see, htmlhint does a line by line parse, which has a very limited power, not allowing simple useful rules such as indentation enforcing, max depth limit, hardcode detection and also optimization rules, such as not allowing require() calls inside an isloop tag.

Isml Linter builds a complex Isml DOM tree, therefore providing more flexibility and power, not to mention the autofix feature, that saves a lot of developer's and reviewer's time.

**Comment by FabiowQuixada** [comment]
> Could we maybe make it configurable so that the developers can choose which one to use?

Hello @SGD1953, thanks for your suggestion. This is perfectly possible, if isml-linter is to be merged, I'll add that option!

**Comment by FabiowQuixada** [comment]
> isml-linter can be used as separate plugin https://marketplace.visualstudio.com/items?itemName=fabiowquixada.vscode-isml-linter

That's true, but that extension is intended for non-Prophet users, as there is an incompability issue, probably due to the fact that both use an isml lsp server.

**Comment by Gektorian** [comment]
Upvoting 👍

**Comment by SqrTT** [comment]
I see no much problem with implementation rules mentioned in isml-linter for htmlhint. 

>  parses the template and builds a full ISML DOM, allowing the usage of powerful rules
implementation details is not an argument to use tools. Even more I found this as disadvantage, because require more resources CPU/memory. Please take in account that linting in VSCode happen for every keyup and rebuilding DOM for that...

**Comment by FabiowQuixada** [comment]
It is decided then :)

Thanks!

**Pull request closed without merging**
