### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by taurgis**
This fixes an issue I was having with the command in the mobile first environment:

npm run compile:scss

It would upload the scss file before it was finished compiling.

### CODE REVIEW

**Comment by taurgis** [comment]
Since this lowers "performance" in general since it will wait for a minimum time, i lowered it to 300ms which is 'almost' instant and seems to be enough to fix the SCSS compilation issue.

**Comment by SqrTT** [comment]
Not sure if this is the right way to fix such issues. Delay higly dependss

**Comment by SqrTT** [comment]
Not sure if this is the right way to fix such issues. Delay highly depends on a user machine, hence is not applicable for all users. I believe there is the better way.

By the way, uploading SCSS files to sandbox doesn't make sense (isn't used either by browser or by sandbox), probably you meant compiled CSS. Also, this means that file is changed several times... probably would be better to change "writer"/compilation logic in [sgmf-scripts](https://bitbucket.org/demandware/sgmf-scripts/src/). 

Interesting if is there the same issue for Eclipse "uploader"?

**Comment by taurgis** [comment]
Yes, I meant the compiled css files. Haven't tried in Eclipse yet. But this issue persists on both Linux and Mac, will check windows tomorrow.

At any rate the css file is uploaded before the sgmf scripts build is finished and we end up without styles on our Sandbox. Haven't taken a look at SFCC new build tools (sgmf) source yet since I haven't got access to the mobile first sitegenesis bitbucket.

**Comment by taurgis** [comment]
The tool that compiles the SCSS is node-sass.

I have been running some tests, this happens to all file types if they take longer than "instantly" to save. This use-case however will not happen often, but is easily reproduce-able (for example saving a large text file).

The developer of chokidar recommends the setting awaitWritFinish to solve this exact problem, but sais you need to set the wait time relatively high to 2 seconds... which is too high for all files.

A solution to fix this selected issue is to maybe have a seperate watcher for a list of filetypes that have this issue. In this case only .css?

**Comment by SqrTT** [comment]
Thank you for input and investigation. I also didn't found a better solution.

**Pull request merged**
